### ISSUE TITLE
iocage package is now py36-iocage

### ISSUE THREAD

**Issue by mvanbaak** [JoergFiedler/freebsd-jail-host#1]
iocage has been rewritten in python and on FreeBSD 11.1 the iocage package is not available anymore.
It's now py36-iocage.

This broke the whole setup.

Any plans on updating to the latest version?

**Comment by JoergFiedler** [comment]
Hi … I will for sure update it as my servers run on FreeBSD … I already did some testing and it seems not to be an super big issue … I will work on this next month … all my ansible projects are in desparate need of some love … I will keep you posted …

thanks for asking …

**Comment by mvanbaak** [comment]
Cool. I was always doing the jail setup manually, as it only involved one static machine at home.

But lately I got a couple of side-projects and all of them involve setting up FreeBSD servers that should run jails.
Because of this I was investigating alternatives to ezjail (while it serves me perfectly until today at home, the side-projects involve external engineers as well)

That's how I bumped into your github account (I already started with my own ansible setup, which is now on hold ;-) )

**Comment by JoergFiedler** [comment]
@mvanbaak there is a branch now that is updated to use the most recent versions of ansible, FreeBSD, … `upgrade-to-most-recent-versions` … I will need some more time before I can merge this … but you are free to try

**Comment by JoergFiedler** [comment]
@mvanbaak I just notice the vagrant image is somehow broken … sudo dies with segmentation fault … I will investigate …

**Comment by mvanbaak** [comment]
Thanks! I can confirm sudo dies here as well.

**Comment by JoergFiedler** [comment]
@mvanbaak I update the branch and also the box file in Vagrant Cloud … the jail host will work now …

**Comment by mvanbaak** [comment]
Works! Thank you!
